### ISSUE TITLE
Style from userstyles.org incomplete

### ISSUE THREAD

**Issue by aalvarado** [cquanu/github-dark#33]
#### What's the issue:

 If you click on show css on the stylish link for this style (https://userstyles.org/styles/128271/github-dark-2-0) it only shows half of the styles when the style is installed, it's missing several lines of css so some elements appear unstyled.
 
#### Steps to reproduce:

Install via stylish on Chrome

#### Solutions:

Maybe there's a limit on Userstyles.org or some abnormal mistake. 

I copy pasted the style from the Github repo and some things that were missing styles now display correctly

#### What version is affected by this problem:

v2.5.0

Thank you for this

**Comment by cquanu** [comment]
That's a very good find! Thanks. It's fixed now. 👍

**Comment by alim0x** [comment]
@cquanu I use the user script with Tampermonkey from userstyles.org

![image](https://cloud.githubusercontent.com/assets/4954007/19220802/78e3dc7e-8e68-11e6-8d97-4eace17f16e8.png)

The user script doesn't work by default,  I think it's because of the missing of the `match` section.

![image](https://cloud.githubusercontent.com/assets/4954007/19220808/bab109ba-8e68-11e6-8bca-05b420c4d3d8.png)

After add line 7 above, the style works with Github.com.

Hope this would be helpful ;)

**Comment by cquanu** [comment]
Hi @alim0x I don't support Tampermonkey ATM.

**Comment by alim0x** [comment]
@cquanu Thanks for your reply, maybe this script is auto-generated by userstyles.org.

Thanks for the beautiful theme :+1:

**Comment by cquanu** [comment]
@alim0x Yup, It's auto-generated by userstyles.org. You're welcome!
